import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface Customer {
  id: string;
  name: string;
  email: string;
}

interface DronePackage {
  id: string;
  name: string;
  code: string;
  price: number;
  category: string;
}

interface DroneJobFormProps {
  onSuccess: () => void;
  onCancel: () => void;
  initialData?: {
    id?: string;
    customer_id?: string;
    package_id?: string;
    property_address: string;
    property_city: string;
    property_state: string;
    property_zip: string;
    property_type: string;
    scheduled_date: string;
    scheduled_time: string;
    pilot_notes: string;
    admin_notes: string;
  };
}

const PROPERTY_TYPES = [
  { value: "residential", label: "Residential" },
  { value: "commercial", label: "Commercial" },
  { value: "construction", label: "Construction" },
  { value: "land", label: "Land/Lot" },
  { value: "industrial", label: "Industrial" },
];

export default function DroneJobForm({ onSuccess, onCancel, initialData }: DroneJobFormProps) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [packages, setPackages] = useState<DronePackage[]>([]);

  const [formData, setFormData] = useState({
    customer_id: initialData?.customer_id || "",
    package_id: initialData?.package_id || "",
    property_address: initialData?.property_address || "",
    property_city: initialData?.property_city || "",
    property_state: initialData?.property_state || "VA",
    property_zip: initialData?.property_zip || "",
    property_type: initialData?.property_type || "residential",
    scheduled_date: initialData?.scheduled_date || "",
    scheduled_time: initialData?.scheduled_time || "",
    pilot_notes: initialData?.pilot_notes || "",
    admin_notes: initialData?.admin_notes || "",
  });

  useEffect(() => {
    const fetchData = async () => {
      const [customersRes, packagesRes] = await Promise.all([
        supabase.from("customers").select("id, name, email").order("name"),
        supabase.from("drone_packages").select("*").eq("active", true).order("price"),
      ]);

      if (customersRes.data) setCustomers(customersRes.data);
      if (packagesRes.data) setPackages(packagesRes.data);
    };
    fetchData();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    const payload = {
      customer_id: formData.customer_id || null,
      package_id: formData.package_id || null,
      property_address: formData.property_address,
      property_city: formData.property_city || null,
      property_state: formData.property_state || null,
      property_zip: formData.property_zip || null,
      property_type: formData.property_type,
      scheduled_date: formData.scheduled_date || null,
      scheduled_time: formData.scheduled_time || null,
      pilot_notes: formData.pilot_notes || null,
      admin_notes: formData.admin_notes || null,
    };

    let error;
    if (initialData?.id) {
      const { error: updateError } = await supabase
        .from("drone_jobs")
        .update(payload)
        .eq("id", initialData.id);
      error = updateError;
    } else {
      // job_number is auto-generated by trigger, so we need to provide a placeholder
      const { error: insertError } = await supabase
        .from("drone_jobs")
        .insert({ ...payload, job_number: "" });
      error = insertError;
    }

    if (error) {
      toast({
        title: "Error saving job",
        description: error.message,
        variant: "destructive",
      });
    } else {
      onSuccess();
    }
    setLoading(false);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-2">
          <Label htmlFor="customer">Customer</Label>
          <Select
            value={formData.customer_id}
            onValueChange={(value) => setFormData({ ...formData, customer_id: value })}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select customer" />
            </SelectTrigger>
            <SelectContent>
              {customers.map((customer) => (
                <SelectItem key={customer.id} value={customer.id}>
                  {customer.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="package">Package</Label>
          <Select
            value={formData.package_id}
            onValueChange={(value) => setFormData({ ...formData, package_id: value })}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select package" />
            </SelectTrigger>
            <SelectContent>
              {packages.map((pkg) => (
                <SelectItem key={pkg.id} value={pkg.id}>
                  {pkg.name} - ${pkg.price}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="space-y-2">
        <Label htmlFor="property_address">Property Address *</Label>
        <Input
          id="property_address"
          value={formData.property_address}
          onChange={(e) => setFormData({ ...formData, property_address: e.target.value })}
          required
        />
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <div className="space-y-2">
          <Label htmlFor="property_city">City</Label>
          <Input
            id="property_city"
            value={formData.property_city}
            onChange={(e) => setFormData({ ...formData, property_city: e.target.value })}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="property_state">State</Label>
          <Input
            id="property_state"
            value={formData.property_state}
            onChange={(e) => setFormData({ ...formData, property_state: e.target.value })}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="property_zip">ZIP</Label>
          <Input
            id="property_zip"
            value={formData.property_zip}
            onChange={(e) => setFormData({ ...formData, property_zip: e.target.value })}
          />
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <div className="space-y-2">
          <Label htmlFor="property_type">Property Type</Label>
          <Select
            value={formData.property_type}
            onValueChange={(value) => setFormData({ ...formData, property_type: value })}
          >
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {PROPERTY_TYPES.map((type) => (
                <SelectItem key={type.value} value={type.value}>
                  {type.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="scheduled_date">Scheduled Date</Label>
          <Input
            id="scheduled_date"
            type="date"
            value={formData.scheduled_date}
            onChange={(e) => setFormData({ ...formData, scheduled_date: e.target.value })}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="scheduled_time">Time</Label>
          <Input
            id="scheduled_time"
            type="time"
            value={formData.scheduled_time}
            onChange={(e) => setFormData({ ...formData, scheduled_time: e.target.value })}
          />
        </div>
      </div>

      <div className="space-y-2">
        <Label htmlFor="pilot_notes">Pilot Notes</Label>
        <Textarea
          id="pilot_notes"
          value={formData.pilot_notes}
          onChange={(e) => setFormData({ ...formData, pilot_notes: e.target.value })}
          placeholder="Access instructions, weather considerations, etc."
          rows={2}
        />
      </div>

      <div className="space-y-2">
        <Label htmlFor="admin_notes">Admin Notes</Label>
        <Textarea
          id="admin_notes"
          value={formData.admin_notes}
          onChange={(e) => setFormData({ ...formData, admin_notes: e.target.value })}
          placeholder="Internal notes..."
          rows={2}
        />
      </div>

      <div className="flex justify-end gap-2 pt-4">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit" disabled={loading}>
          {loading ? "Saving..." : initialData?.id ? "Update Job" : "Create Job"}
        </Button>
      </div>
    </form>
  );
}
