-- M6 (forward half of history reconciliation)
--
-- public.invoices and public.projects were dropped out-of-band on the remote
-- (verified 2026-07-27: neither relation exists in pg_class for schema public).
-- The two 2026-01 migrations that created them are still in history and are
-- deliberately NOT edited — rewriting an applied migration diverges its
-- checksum against supabase_migrations.schema_migrations and breaks `db push`.
--
-- Without this file `supabase db reset` replays those creates and rebuilds two
-- dead tables that prod does not have. This is the forward correction.
--
-- Created by  : 20260107184339 (invoices), 20260108144130 (projects)
-- additive    : no  — destructive, but only of relations already absent on prod
-- idempotent  : yes — `drop table if exists`
-- reversible  : yes — re-running the 2026-01 creates rebuilds them
--
--
-- WHAT STILL REFERENCES THEM
--
-- An earlier draft of this header claimed nothing references these tables.
-- That was false. Nine call sites remain (verified by grep 2026-07-27):
--
--   invoices (7)
--     supabase/functions/invoice-mark-viewed/index.ts:31,46      [DEPLOYED]
--     supabase/functions/invoice-payment-claim/index.ts:46,81    [DEPLOYED]
--     supabase/functions/send-service-invoice-email/index.ts:33  [DEPLOYED]
--     src/pages/CustomerInvoice.tsx:107        (route /invoice/:token)
--     src/pages/CustomerProposal.tsx:197       (route /proposal/:token)
--   projects (2)
--     supabase/functions/send-project-status-email/index.ts:105,244 [DEPLOYED]
--
-- [DEPLOYED] = the function answers a CORS preflight on
-- <project>.supabase.co/functions/v1/<name> with HTTP 200, checked 2026-07-27.
--
-- Plus two plpgsql triggers on public.proposals that INSERT into the dropped
-- relations. They live on proposals, not on invoices/projects, and plpgsql
-- bodies are not dependency-tracked, so DROP ... CASCADE does NOT remove them:
--   on_proposal_approved_create_invoice  -> create_invoice_from_approved_proposal()
--   trigger_create_project_from_proposal -> create_project_from_proposal()
-- No migration drops either one. Whether they are still attached on prod cannot
-- be checked read-only through PostgREST (pg_catalog is not exposed); run the
-- trigger query below with SQL access to confirm.
--
--
-- WHY THE DROP IS STILL SAFE
--
-- 1. Both relations are ALREADY GONE from prod. GET /rest/v1/invoices and
--    GET /rest/v1/projects both return HTTP 404 (PGRST205, undefined table),
--    checked 2026-07-27. On prod this file is a literal no-op.
-- 2. So it cannot break anything that is not already broken. All nine call
--    sites and both triggers fail against prod TODAY, independently of this
--    migration. This file changes `supabase db reset` only, and it changes it
--    in the direction of matching prod. Local stops disagreeing with prod about
--    whether these code paths work; the answer is "they do not", everywhere.
-- 3. CASCADE has nothing extra to take. No migration declares an inbound FK to
--    either relation (grep 'REFERENCES .*(invoices|projects)' over
--    supabase/migrations = 0 hits), so the cascade reaches only each table's own
--    indexes, RLS policies and on-table triggers.
-- 4. No migration ordered after this one references either relation as a table,
--    so `db reset` does not fail downstream. The nearest neighbours were
--    checked: 20260226120000_payments.sql and 20260728093000 mention "invoice"
--    only in prose, and 20260308120000_add_archived_at_columns.sql (which does
--    ALTER both tables) is ordered BEFORE this file.
-- 5. SORTIE CONTRACT: untouched. Neither relation joins drone_jobs. The shared
--    helper generate_document_number(prefix, table_name, column_name) takes the
--    table as a TEXT argument, so it carries no parse-time dependency on
--    invoices/projects and survives the cascade intact — which matters because
--    generate_drone_job_number() calls it to mint job_number, the column sortie
--    deliberately keeps out of WRITABLE_FIELDS.
--
--
-- WHAT THIS FILE DELIBERATELY DOES NOT DO
--
-- It does not drop the two proposals triggers. Doing so would flip proposal
-- approval from "errors loudly" to "succeeds and silently produces no invoice
-- and no project", which is a product decision about whether service-side
-- invoicing is coming back, not a schema cleanup. Left for the owner, flagged
-- here so it is not rediscovered as a surprise.
--
--
-- verification:
--   -- (a) relations absent, both before (prod) and after (fresh db reset)
--   select c.relname
--     from pg_class c join pg_namespace n on n.oid = c.relnamespace
--    where n.nspname = 'public' and c.relname in ('invoices','projects');
--   -- expect 0 rows
--
--   -- (b) the two orphaned triggers on proposals - expect 0 rows once the
--   --     owner decides; non-zero today is the known open item above
--   select t.tgname
--     from pg_trigger t
--    where t.tgrelid = 'public.proposals'::regclass
--      and t.tgname in ('on_proposal_approved_create_invoice',
--                       'trigger_create_project_from_proposal');
--
--   -- (c) no inbound FK survived pointing at either relation - expect 0 rows
--   select conname, conrelid::regclass
--     from pg_constraint
--    where confrelid in ('public.invoices'::regclass, 'public.projects'::regclass);
--   -- (errors with "relation does not exist" once dropped, which is also a pass)

drop table if exists public.invoices cascade;
drop table if exists public.projects cascade;
